### ISSUE TITLE
topicZone for titlealts seems to be ignored

### ISSUE THREAD

**Issue by dduffy331** [dita4publishers/org.dita4publishers.word2dita#51]
Issue: I want to convert from Word to DITA a heading level and text but I want to create both the title element and the titlealts/searchtitle element in the same topic. The resulting topicref has the title element but the topicZone to titleAlts seems to be ignored (not in DITA). 

This is the mapping code I am using:

`<style styleName="Demo/exercise icon box - heading"
      structureType="topicTitle"
      topicDoc="yes"
      topicType="concept"
      bodyType="conbody"
      format="concept"
      topicrefType="topicref"
      tagName="title"
      level="3"
      topicZone="titleAlts"
      topicOutputclass="exercise"
	/>`

Results in:
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE concept PUBLIC "-//OASIS//DTD DITA Concept//EN" "concept.dtd">
<concept id="topic_6_2_1" xml:lang="en-US" outputclass="exercise">
  <title>Exercise 4.2: Personalize the XYZ</title>
  <conbody>
	 <p>In this exercise, you will personalize the XYZ.
	 </p>
	 <section>
		<p>Before you begin:
		</p>
		<ul>`...

**Comment by drmacro** [comment]
I'm looking at this issue.

My question: why do you want to generate *both* title and titleAlts when they will be identical?

DITA semantics are that the title also serves as the alternative titles if a given alternative title is not specified.

Or are you simply trying to poplulate the element so that it's there for authors following conversion?

Looking at this issue I think you cannot do what you're trying to do with the current code. 

The intent of the current code is that a paragraph can be either the title or an alternative title, but not both.

So the result you're getting is "correct" in that it reflects the tagname you specified (title) but it was created during the title alts processing the code does. But since you didn't have a separate title-providing paragraph the resulting topic was still valid (because it had a title where one is required).

If your requirement is "Generate title alts when also generating a title using the same paragraph content" then I think that's a reasonable requirement--I can see the value if you need authors to adjust title alts after the fact.

You can do this today using a custom post-process in the final-fixup stage (match on title elements that do not have following siblings with the title alts you want) but this seems like a common-enough case to be worth providing for in the style-to-tag map.

**Comment by drmacro** [comment]
Implementing this by adding new attributes to the style-to-tag map:
* @generateTitleAlts on paragraphStyle. Value is list of titlealts elements to generate. Use when structureType is "topicTitle".
* @titlealtsType on topicProperties. Specifies the tag name for the titlealts container if it is different from "titlealts"

With those two attributes can generate title alts during final fixup processing when the specified title alts are not already present (because they were generated explicitly from a separate paragraph).

Also discovered that existing code for generating title alts does not create valid DITA, so will fix that too.

**Comment by dduffy331** [comment]
What we wanted to change was the searchtitle element within the titlealts. Searchtitles are used within a CCMS to find content with a different naming convention in case you have multiple Prerequisites topics. You can add content to the searchtitle to differentiate the topics by adding unique content such as for user guide or for product A.

**Comment by drmacro** [comment]
So if you want the word2dita process to generate a searchTitle different from the title then you need a separate paragraph in the Word doc with the search title content--in that case you would set the tagname to "searchtitle" and the topicZone to titleAlts. That worked before but did not wrap the alternative titles in the required titlealts element.

I've fixed the generation of titlealts as part of addressing this bug.

If you just wanted to generate a searchtitle element so the author could subsequently modify it, that requirement is now satisfied with this fix and the new "generateTitleAlts" attribute on the paragraphStyle element.
