### ISSUE TITLE
cross-references lost in DITA files

### ISSUE THREAD

**Issue by PieterjanVandenweghe** [dita4publishers/org.dita4publishers.word2dita#53]
* References are lost in the DITA files when the cross-references are added in Word via **Insert > Cross-reference**:
              - Reference to a figure/table
              - Reference to a chapter
* References are resolved correctly in the DITA files when they are added in Word via **Insert > Link**
              - Reference to a chapter
              - Reference to a bookmark

Sample document with the different cases: [Sample-document.docx](https://github.com/dita4publishers/org.dita4publishers.word2dita/files/5373223/Sample-document.docx)

I am using the plugin that is by default added to the build-in DITA-OT from Oxygen22.1.

**Comment by drmacro** [comment]
So the basic problem is the word2dita transform currently ignores all field codes, which is why it's ignored.

I will see what I can do to handle field codes and implement this reference mechanism.

**Comment by drmacro** [comment]
I have the core of complex field handling in place and am now generating an xref from a REF field but with a bogus @href value.

Next step is to figure out how to generate a good @href value. One potential challenge here is that the REF is to a bookmark that needs to become the ID of something that can be cross referenced to.

**Comment by drmacro** [comment]
I've taken a first pass at implementing the REF complex field such that it results in a *working* xref for the test document.
However, the limitation is that at the time the xref is constructed it's not possible to know in all cases what the real target should be.
In the case of the sample doc, the refs are to bookmarks within  paragraphs that map directly to <title> elements (a topic title and a figure title).
Thus the resulting DITA has cross references to the <title> elements, not to their containers.
There's a pre-existing comment in the code (I already had code for making xrefs from references to bookmarks, just needed to hook it up to REF fields) to the effect that correcting the ref can be handled with post processing since the specific rules for ID generation or target determination may be different for different installations. This post processing would be done as an extension in the final-fixup mode.
There may be a more general solution that I haven't seen, at least for common cases, but this implementation at least meets the minimal requirement of making working references that can then be refined in the editor or via post processing.
This code creates a general framework for handling all complex fields, which is nice.
This feature also benefited from a change I happened to make to support my day job that made it easy to add handling of runs that make up complex fields.

**Comment by PieterjanVandenweghe** [comment]
Thank you for the effort and this extra info. The reference to the <title> element is already a big help for me at the moment and I can indeed refine it during post-processing if necessary.
