### ISSUE TITLE
Unable to change file extension

### ISSUE THREAD

**Issue by juliovaz** [dita4publishers/org.dita4publishers.word2dita#59]
There is no properties file for the plugin and even looking for the topicExtension parameter and overwriting it does not seem to change the default of .dita. Tried multiple files in the plugin to no avail.

**Comment by drmacro** [comment]
What version of Open Toolkit are you using?

**Comment by juliovaz** [comment]
For my current testing, so I know it works for my folks,  2.4.6.

**Comment by drmacro** [comment]
The Ant parameter to use to set the topic extension is "w2d.topic.extension":
```
dita -i someword.docx -f word2dita -Dw2d.style-to-tag-map=/../../style2tagMap.xml -Dw2d.topic.extension=.xml
```

The documentation for the ant parameters is here: http://www.dita4publishers.org/d4p-users-guide/user_docs/d4p-users-guide/word2dita/word-to-dita-plugin-usage.html

I realize the path to the docs is not completely obvious  (as a side effect of my incomplete effort to move Word2DITA to its own project instead of being part of DITA for publishers).
